/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-05 05:04:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>EShopper - Bootstrap Shop Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

String user = (String)session.getAttribute("user");
String x = (String)request.getAttribute("a");


if(user==null && x==null)
{
	request.setAttribute("msg", "Please login first!!!");
	request.getRequestDispatcher("login.jsp").forward(request, response);
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row bg-secondary py-2 px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-6 d-none d-lg-block\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-dark\" href=\"\">FAQs</a>\r\n");
      out.write("                    <span class=\"text-muted px-2\">|</span>\r\n");
      out.write("                    <a class=\"text-dark\" href=\"\">Help</a>\r\n");
      out.write("                    <span class=\"text-muted px-2\">|</span>\r\n");
      out.write("                    <a class=\"text-dark\" href=\"\">Support</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 text-center text-lg-right\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-dark px-2\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-dark px-2\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-dark px-2\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-dark px-2\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-dark pl-2\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row align-items-center py-3 px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <a href=\"\" class=\"text-decoration-none\">\r\n");
      out.write("                    <h1 class=\"m-0 display-5 font-weight-semi-bold\"><span class=\"text-primary font-weight-bold border px-3 mr-1\">E</span>Shopper</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 col-6 text-left\">\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search for products\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <span class=\"input-group-text bg-transparent text-primary\">\r\n");
      out.write("                                <i class=\"fa fa-search\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-6 text-right\">\r\n");
      out.write("                <a href=\"\" class=\"btn border\">\r\n");
      out.write("                    <i class=\"fas fa-heart text-primary\"></i>\r\n");
      out.write("                    <span class=\"badge\">0</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"\" class=\"btn border\">\r\n");
      out.write("                    <i class=\"fas fa-shopping-cart text-primary\"></i>\r\n");
      out.write("                    <span class=\"badge\">0</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid mb-5\">\r\n");
      out.write("        <div class=\"row border-top px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <a class=\"btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100\" data-toggle=\"collapse\" href=\"#navbar-vertical\" style=\"height: 65px; margin-top: -1px; padding: 0 30px;\">\r\n");
      out.write("                    <h6 class=\"m-0\">Categories</h6>\r\n");
      out.write("                    <i class=\"fa fa-angle-down text-dark\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <nav class=\"collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0\" id=\"navbar-vertical\">\r\n");
      out.write("                    <div class=\"navbar-nav w-100 overflow-hidden\" style=\"height: 410px\">\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link\" data-toggle=\"dropdown\">Dresses <i class=\"fa fa-angle-down float-right mt-1\"></i></a>\r\n");
      out.write("                            <div class=\"dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0\">\r\n");
      out.write("                                <a href=\"mendress.jsp\" class=\"dropdown-item\">Men's Dresses</a>\r\n");
      out.write("                                <a href=\"womendress.jsp\" class=\"dropdown-item\">Women's Dresses</a>\r\n");
      out.write("                                <a href=\"\" class=\"dropdown-item\">Baby's Dresses</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Shirts</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Jeans</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Swimwear</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Sleepwear</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Sportswear</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Jumpsuits</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Blazers</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Jackets</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Shoes</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0\">\r\n");
      out.write("                    <a href=\"\" class=\"text-decoration-none d-block d-lg-none\">\r\n");
      out.write("                        <h1 class=\"m-0 display-5 font-weight-semi-bold\"><span class=\"text-primary font-weight-bold border px-3 mr-1\">E</span>Shopper</h1>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\">\r\n");
      out.write("                        <div class=\"navbar-nav mr-auto py-0\">\r\n");
      out.write("                            <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                            <a href=\"shop.jsp\" class=\"nav-item nav-link\">Shop</a>\r\n");
      out.write("                            <a href=\"detail.jsp\" class=\"nav-item nav-link\">Shop Detail</a>\r\n");
      out.write("                            <div class=\"nav-item dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("                                <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                    <a href=\"cart.jsp\" class=\"dropdown-item\">Shopping Cart</a>\r\n");
      out.write("                                    <a href=\"checkout.jsp\" class=\"dropdown-item\">Checkout</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"contact.jsp\" class=\"nav-item nav-link\">Contact</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"navbar-nav ml-auto py-0\">\r\n");
      out.write("                            <a href=\"logout\" class=\"nav-item nav-link\">Logout</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div id=\"header-carousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                    <div class=\"carousel-inner\">\r\n");
      out.write("                        <div class=\"carousel-item active\" style=\"height: 410px;\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/carousel-1.jpg\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                                <div class=\"p-3\" style=\"max-width: 700px;\">\r\n");
      out.write("                                    <h4 class=\"text-light text-uppercase font-weight-medium mb-3\">10% Off Your First Order</h4>\r\n");
      out.write("                                    <h3 class=\"display-4 text-white font-weight-semi-bold mb-4\">Fashionable Dress</h3>\r\n");
      out.write("                                    <a href=\"\" class=\"btn btn-light py-2 px-3\">Shop Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\" style=\"height: 410px;\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/carousel-2.jpg\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                                <div class=\"p-3\" style=\"max-width: 700px;\">\r\n");
      out.write("                                    <h4 class=\"text-light text-uppercase font-weight-medium mb-3\">10% Off Your First Order</h4>\r\n");
      out.write("                                    <h3 class=\"display-4 text-white font-weight-semi-bold mb-4\">Reasonable Price</h3>\r\n");
      out.write("                                    <a href=\"\" class=\"btn btn-light py-2 px-3\">Shop Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#header-carousel\" data-slide=\"prev\">\r\n");
      out.write("                        <div class=\"btn btn-dark\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                            <span class=\"carousel-control-prev-icon mb-n2\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"carousel-control-next\" href=\"#header-carousel\" data-slide=\"next\">\r\n");
      out.write("                        <div class=\"btn btn-dark\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                            <span class=\"carousel-control-next-icon mb-n2\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Featured Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5 pb-3\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fa fa-check text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Quality Product</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fa fa-shipping-fast text-primary m-0 mr-2\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Free Shipping</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fas fa-exchange-alt text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">14-Day Return</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fa fa-phone-volume text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">24/7 Support</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Featured End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Categories Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5 pb-3\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 pb-1\">\r\n");
      out.write("                <div class=\"cat-item d-flex flex-column border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <p class=\"text-right\">15 Products</p>\r\n");
      out.write("                    <a href=\"\" class=\"cat-img position-relative overflow-hidden mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/cat-1.jpg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Men's dresses</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 pb-1\">\r\n");
      out.write("                <div class=\"cat-item d-flex flex-column border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <p class=\"text-right\">15 Products</p>\r\n");
      out.write("                    <a href=\"\" class=\"cat-img position-relative overflow-hidden mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/cat-2.jpg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Women's dresses</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 pb-1\">\r\n");
      out.write("                <div class=\"cat-item d-flex flex-column border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <p class=\"text-right\">15 Products</p>\r\n");
      out.write("                    <a href=\"\" class=\"cat-img position-relative overflow-hidden mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/cat-3.jpg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Baby's dresses</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 pb-1\">\r\n");
      out.write("                <div class=\"cat-item d-flex flex-column border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <p class=\"text-right\">15 Products</p>\r\n");
      out.write("                    <a href=\"\" class=\"cat-img position-relative overflow-hidden mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/cat-4.jpg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Accerssories</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 pb-1\">\r\n");
      out.write("                <div class=\"cat-item d-flex flex-column border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <p class=\"text-right\">15 Products</p>\r\n");
      out.write("                    <a href=\"\" class=\"cat-img position-relative overflow-hidden mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/cat-5.jpg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Bags</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 pb-1\">\r\n");
      out.write("                <div class=\"cat-item d-flex flex-column border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <p class=\"text-right\">15 Products</p>\r\n");
      out.write("                    <a href=\"\" class=\"cat-img position-relative overflow-hidden mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/cat-6.jpg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Shoes</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Categories End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Offer Start -->\r\n");
      out.write("    <div class=\"container-fluid offer pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5\">\r\n");
      out.write("            <div class=\"col-md-6 pb-4\">\r\n");
      out.write("                <div class=\"position-relative bg-secondary text-center text-md-right text-white mb-2 py-5 px-5\">\r\n");
      out.write("                    <img src=\"img/offer-1.png\" alt=\"\">\r\n");
      out.write("                    <div class=\"position-relative\" style=\"z-index: 1;\">\r\n");
      out.write("                        <h5 class=\"text-uppercase text-primary mb-3\">20% off the all order</h5>\r\n");
      out.write("                        <h1 class=\"mb-4 font-weight-semi-bold\">Spring Collection</h1>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-outline-primary py-md-2 px-md-3\">Shop Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 pb-4\">\r\n");
      out.write("                <div class=\"position-relative bg-secondary text-center text-md-left text-white mb-2 py-5 px-5\">\r\n");
      out.write("                    <img src=\"img/offer-2.png\" alt=\"\">\r\n");
      out.write("                    <div class=\"position-relative\" style=\"z-index: 1;\">\r\n");
      out.write("                        <h5 class=\"text-uppercase text-primary mb-3\">20% off the all order</h5>\r\n");
      out.write("                        <h1 class=\"mb-4 font-weight-semi-bold\">Winter Collection</h1>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-outline-primary py-md-2 px-md-3\">Shop Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Offer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Products Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"text-center mb-4\">\r\n");
      out.write("            <h2 class=\"section-title px-5\"><span class=\"px-2\">Trandy Products</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row px-xl-5 pb-3\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-4.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-5.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-6.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-7.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-8.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Products End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Subscribe Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary my-5\">\r\n");
      out.write("        <div class=\"row justify-content-md-center py-5 px-xl-5\">\r\n");
      out.write("            <div class=\"col-md-6 col-12 py-5\">\r\n");
      out.write("                <div class=\"text-center mb-2 pb-2\">\r\n");
      out.write("                    <h2 class=\"section-title px-5 mb-3\"><span class=\"bg-secondary px-2\">Stay Updated</span></h2>\r\n");
      out.write("                    <p>Amet lorem at rebum amet dolores. Elitr lorem dolor sed amet diam labore at justo ipsum eirmod duo labore labore.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control border-white p-4\" placeholder=\"Email Goes Here\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <button class=\"btn btn-primary px-4\">Subscribe</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Subscribe End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Products Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"text-center mb-4\">\r\n");
      out.write("            <h2 class=\"section-title px-5\"><span class=\"px-2\">Just Arrived</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row px-xl-5 pb-3\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-4.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-5.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-6.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-7.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <img class=\"img-fluid w-100\" src=\"img/product-8.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Colorful Stylish Shirt</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>$123.00</h6><h6 class=\"text-muted ml-2\"><del>$123.00</del></h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>View Detail</a>\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Add To Cart</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Products End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"row px-xl-5\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <div class=\"owl-carousel vendor-carousel\">\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-4.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-5.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-6.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-7.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-8.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Vendor End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-dark mt-5 pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5 pt-5\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5\">\r\n");
      out.write("                <a href=\"\" class=\"text-decoration-none\">\r\n");
      out.write("                    <h1 class=\"mb-4 display-5 font-weight-semi-bold\"><span class=\"text-primary font-weight-bold border border-white px-3 mr-1\">E</span>Shopper</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt text-primary mr-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-envelope text-primary mr-3\"></i>info@example.com</p>\r\n");
      out.write("                <p class=\"mb-0\"><i class=\"fa fa-phone-alt text-primary mr-3\"></i>+012 345 67890</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-8 col-md-12\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                        <h5 class=\"font-weight-bold text-dark mb-4\">Quick Links</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"index.html\"><i class=\"fa fa-angle-right mr-2\"></i>Home</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"shop.html\"><i class=\"fa fa-angle-right mr-2\"></i>Our Shop</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"detail.html\"><i class=\"fa fa-angle-right mr-2\"></i>Shop Detail</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"cart.html\"><i class=\"fa fa-angle-right mr-2\"></i>Shopping Cart</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"checkout.html\"><i class=\"fa fa-angle-right mr-2\"></i>Checkout</a>\r\n");
      out.write("                            <a class=\"text-dark\" href=\"contact.html\"><i class=\"fa fa-angle-right mr-2\"></i>Contact Us</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                        <h5 class=\"font-weight-bold text-dark mb-4\">Quick Links</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"index.html\"><i class=\"fa fa-angle-right mr-2\"></i>Home</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"shop.html\"><i class=\"fa fa-angle-right mr-2\"></i>Our Shop</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"detail.html\"><i class=\"fa fa-angle-right mr-2\"></i>Shop Detail</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"cart.html\"><i class=\"fa fa-angle-right mr-2\"></i>Shopping Cart</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"checkout.html\"><i class=\"fa fa-angle-right mr-2\"></i>Checkout</a>\r\n");
      out.write("                            <a class=\"text-dark\" href=\"contact.html\"><i class=\"fa fa-angle-right mr-2\"></i>Contact Us</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                        <h5 class=\"font-weight-bold text-dark mb-4\">Newsletter</h5>\r\n");
      out.write("                        <form action=\"\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control border-0 py-4\" placeholder=\"Your Name\" required=\"required\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control border-0 py-4\" placeholder=\"Your Email\"\r\n");
      out.write("                                    required=\"required\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <button class=\"btn btn-primary btn-block border-0 py-3\" type=\"submit\">Subscribe Now</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row border-top border-light mx-xl-5 py-4\">\r\n");
      out.write("            <div class=\"col-md-6 px-xl-0\">\r\n");
      out.write("                <p class=\"mb-md-0 text-center text-md-left text-dark\">\r\n");
      out.write("                    &copy; <a class=\"text-dark font-weight-semi-bold\" href=\"#\">Your Site Name</a>. All Rights Reserved. Designed\r\n");
      out.write("                    by\r\n");
      out.write("                    <a class=\"text-dark font-weight-semi-bold\" href=\"https://htmlcodex.com\">HTML Codex</a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 px-xl-0 text-center text-md-right\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"img/payments.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-primary back-to-top\"><i class=\"fa fa-angle-double-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Javascript File -->\r\n");
      out.write("    <script src=\"mail/jqBootstrapValidation.min.js\"></script>\r\n");
      out.write("    <script src=\"mail/contact.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
